[nc] fix BAKE_FILE
Signed-off-by: Nic Cheneweth <nchenewe@thoughtworks.com>

diff --git a/sign-manifest/action.yaml b/sign-manifest/action.yaml
--- a/sign-manifest/action.yaml
+++ b/sign-manifest/action.yaml
@@ -65,13 +65,13 @@ runs:
         echo "Signing released images."
 
         if [[ ! -f "$BAKE_FILE" ]]; then
-          echo "Bake file not found: $BAKEFILE" >&2
+          echo "Bake file not found: $BAKE_FILE" >&2
           exit 1
         fi
         [[ -z "$RELEASE_TAG" ]] && RELEASE_TAG="$GITHUB_REF_NAME"
         eval "RELEASE_TAG=\"$RELEASE_TAG\""
 
-        echo "Using bake file: $BAKEFILE"
+        echo "Using bake file: $BAKE_FILE"
         echo "release tag: $RELEASE_TAG"
 
         # Extract all targets and their tags
diff --git a/tagx/action.yaml b/tagx/action.yaml
--- a/tagx/action.yaml
+++ b/tagx/action.yaml
@@ -49,8 +49,8 @@ runs:
 
         echo "Adding release tag to existing image manifests."
 
-        if [[ ! -f "$BAKEFILE" ]]; then
-          echo "Bake file not found: $BAKEFILE" >&2
+        if [[ ! -f "$BAKE_FILE" ]]; then
+          echo "Bake file not found: $BAKE_FILE" >&2
           exit 1
         fi
         [[ -z "$TAG" ]] && TAG="dev.${GITHUB_SHA::7}"
@@ -71,7 +71,7 @@ runs:
           | .value.tags[]
           | [$name, .]
           | @tsv
-        ' "$BAKEFILE" |
+        ' "$BAKE_FILE" |
         while IFS=$'\t' read -r target_name raw_tag; do
           image_ref="$raw_tag"
 
